# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build test

      - name: Publish artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app.jar
          path: build/libs/shadow-stable.jar

  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Zip Folder
        run: zip -r release.zip frontend/dist
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: release.zip
          path: release.zip

  deploy:
    needs: [build_kotlin, build-node]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download Gradle artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: app.jar
          # Destination path
          path: dist/app.jar

      - name: Download Statics artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: release.zip
          # Destination path
          path: dist/release.zip

      - name: Unzip Statics
        run: unzip dist/release.zip

      - name: Promote
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: release/
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Purge artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          # Human readable expire duration
          expire-in: 2d
          # Github auth token
          token: ${{ secrets.GH_TOKEN }}
