# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ frontend ]
  pull_request:
    branches: [ frontend ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Zip Folder
      run: zip -r release.zip frontend/dist
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: release-${{github.sha}}.zip
        path: release-${{github.sha}}.zip
